import { test, expect } from '@playwright/test';

test('Positive Test 3 - Skill and Interest Validation', async ({ page }) => {
  await page.goto('http://localhost:5000/page/1');
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('Arpita Kumari');
  await page.getByRole('textbox', { name: 'Full Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email *' }).fill('arpita@example.com');
  await page.getByRole('textbox', { name: 'Email *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Phone Number *' }).fill('+91 7562560945');
  await page.getByRole('textbox', { name: 'Phone Number *' }).press('Tab');
  await page.getByLabel('University *').press('ArrowDown');
  await page.getByLabel('University *').selectOption('State University');
  await page.getByRole('textbox', { name: 'Major/Degree *' }).click();
  await page.getByRole('textbox', { name: 'Major/Degree *' }).fill('Data Science and Management');
  await page.getByRole('textbox', { name: 'Expected Graduation *' }).click();
  await page.getByRole('textbox', { name: 'Expected Graduation *' }).fill('2027-12-08');
  await page.getByRole('button', { name: 'Resume Upload *' }).click();
  await page.getByRole('button', { name: 'Resume Upload *' }).setInputFiles('Rahul_S_RS_Design_Freelancer_Resume.pdf');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Business Analytics and Programming');
  await page.getByRole('textbox', { name: 'Course Code' }).click();
  await page.getByRole('textbox', { name: 'Course Code' }).fill('CS 458');
  await page.getByRole('textbox', { name: 'Course Code' }).press('Tab');
  await page.getByLabel('Grade Obtained *').selectOption('A');
  await page.getByLabel('Grade Obtained *').press('Tab');
  await page.getByLabel('Semester/Year').press('ArrowDown');
  await page.getByLabel('Semester/Year').selectOption('Spring 2023');
  await page.getByLabel('Semester/Year').press('ArrowDown');
  await page.getByLabel('Semester/Year').selectOption('Fall 2023');
  await page.getByLabel('Semester/Year').press('ArrowDown');
  await page.getByLabel('Semester/Year').selectOption('Spring 2024');
  await page.getByLabel('Semester/Year').press('ArrowDown');
  await page.getByLabel('Semester/Year').selectOption('Fall 2024');
  await page.getByLabel('Semester/Year').press('ArrowDown');
  await page.getByLabel('Semester/Year').selectOption('Spring 2025');
  await page.getByLabel('Semester/Year').press('ArrowDown');
  await page.getByLabel('Semester/Year').selectOption('Fall 2025');
  await page.getByRole('button', { name: 'Add Course' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Machine Learning');
  await page.getByRole('textbox', { name: 'Course Code' }).click();
  await page.getByRole('textbox', { name: 'Course Code' }).fill('DS 1001');
  await page.getByLabel('Grade Obtained *').selectOption('B+');
  await page.getByLabel('Semester/Year').selectOption('Fall 2025');
  await page.getByRole('button', { name: 'Add Course' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('checkbox', { name: 'Python' }).check();
  await page.getByRole('checkbox', { name: 'Java', exact: true }).check();
  await page.getByRole('checkbox', { name: 'JavaScript' }).check();
  await page.getByRole('checkbox', { name: 'SQL' }).check();
  await page.getByRole('checkbox', { name: 'HTML/CSS' }).check();
  await page.getByRole('checkbox', { name: 'React' }).check();
  await page.getByRole('checkbox', { name: 'Node.js' }).check();
  await page.getByRole('checkbox', { name: 'Git' }).check();
  await page.getByRole('checkbox', { name: 'Machine Learning' }).check();
  await page.getByRole('checkbox', { name: 'Docker' }).check();
  await page.getByRole('checkbox', { name: 'Communication' }).check();
  await page.getByRole('checkbox', { name: 'Teamwork' }).check();
  await page.getByRole('checkbox', { name: 'Problem Solving' }).check();
  await page.getByRole('checkbox', { name: 'Leadership' }).check();
  await page.getByRole('checkbox', { name: 'Time Management' }).check();
  await page.getByRole('checkbox', { name: 'Attention to Detail' }).check();
  await page.getByRole('checkbox', { name: 'Critical Thinking' }).check();
  await page.getByText('Machine Learning').nth(1).click();
  await page.getByText('Flexible (any semester)').click();
  await page.getByRole('textbox', { name: 'Any additional information' }).click();
  await page.getByRole('textbox', { name: 'Any additional information' }).fill('Machine Learning (or data Science)');
  await page.getByRole('textbox', { name: 'Any additional information' }).click();
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Any additional information' }).fill('Machine Learning (or Data Science)');
  await page.getByRole('button', { name: 'Submit' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Save Draft' }).click();
});