import { test, expect } from '@playwright/test';

test('Positive Test 2 - Application Without Work Experience', async ({ page }) => {
  await page.goto('http://localhost:5000/page/1');
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('John Doe');
  await page.getByRole('textbox', { name: 'Full Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email *' }).fill('john@example.com');
  await page.getByRole('textbox', { name: 'Email *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Phone Number *' }).fill('+91 9804835607');
  await page.getByRole('textbox', { name: 'Phone Number *' }).press('Tab');
  await page.getByLabel('University *').press('ArrowDown');
  await page.getByLabel('University *').selectOption('State University');
  await page.getByLabel('University *').press('ArrowDown');
  await page.getByLabel('University *').selectOption('Tech Institute');
  await page.getByLabel('University *').press('Tab');
  await page.getByRole('textbox', { name: 'Major/Degree *' }).fill('Computer Science');
  await page.getByRole('textbox', { name: 'Expected Graduation *' }).click();
  await page.getByRole('textbox', { name: 'Expected Graduation *' }).fill('2027-11-05');
  await page.getByRole('button', { name: 'Resume Upload *' }).click();
  await page.getByRole('button', { name: 'Resume Upload *' }).setInputFiles('Rahul_S_RS_Design_Freelancer_Resume.pdf');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Data Structures and Algorithm with Java');
  await page.getByRole('textbox', { name: 'Course Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Course Code' }).fill('CS 2060');
  await page.getByRole('textbox', { name: 'Course Code' }).press('Tab');
  await page.getByLabel('Grade Obtained *').selectOption('B+');
  await page.getByLabel('Grade Obtained *').press('Tab');
  await page.getByLabel('Semester/Year').selectOption('Fall 2025');
  await page.getByRole('button', { name: 'Add Course' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Computational Thinking');
  await page.getByRole('textbox', { name: 'Course Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Course Code' }).fill('CS 2061');
  await page.getByRole('textbox', { name: 'Course Code' }).press('Tab');
  await page.getByLabel('Grade Obtained *').selectOption('A');
  await page.getByLabel('Grade Obtained *').selectOption('A-');
  await page.getByLabel('Semester/Year').selectOption('Fall 2025');
  await page.getByRole('button', { name: 'Add Course' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('checkbox', { name: 'Java', exact: true }).check();
  await page.getByRole('checkbox', { name: 'React' }).check();
  await page.getByRole('checkbox', { name: 'HTML/CSS' }).check();
  await page.getByRole('checkbox', { name: 'Node.js' }).check();
  await page.getByRole('checkbox', { name: 'Git' }).check();
  await page.getByRole('checkbox', { name: 'Docker' }).check();
  await page.getByRole('checkbox', { name: 'JavaScript' }).check();
  await page.getByRole('checkbox', { name: 'SQL' }).check();
  await page.getByRole('checkbox', { name: 'Communication' }).check();
  await page.getByRole('checkbox', { name: 'Teamwork' }).check();
  await page.getByRole('checkbox', { name: 'Time Management' }).check();
  await page.getByRole('checkbox', { name: 'Attention to Detail' }).check();
  await page.getByRole('checkbox', { name: 'Critical Thinking' }).check();
  await page.getByRole('radio', { name: 'Full-Stack Development' }).check();
  await page.getByText('Spring 2026 (January–April)').click();
  await page.getByRole('textbox', { name: 'Any additional information' }).click();
  await page.getByRole('textbox', { name: 'Any additional information' }).fill('Interested in working as a full stack developer intern.');
  await page.getByRole('button', { name: 'Submit' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Save Draft' }).click();
});