import { test, expect } from '@playwright/test';

test('Positive Test 1 - Complete Internship Application Submission with work experience', async ({ page }) => {
  await page.goto('http://localhost:5000/page/1');
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('Raunak Sen');
  await page.getByRole('textbox', { name: 'Full Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email *' }).fill('raunak@example.com');
  await page.getByRole('textbox', { name: 'Email *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Phone Number *' }).fill('+91 8902921850');
  await page.getByRole('textbox', { name: 'Phone Number *' }).press('Tab');
  await page.getByLabel('University *').selectOption('Tech Institute');
  await page.getByRole('textbox', { name: 'Major/Degree *' }).click();
  await page.getByRole('textbox', { name: 'Major/Degree *' }).fill('Data Science');
  await page.getByRole('textbox', { name: 'Major/Degree *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Expected Graduation *' }).fill('0009-01-02');
  await page.getByRole('textbox', { name: 'Expected Graduation *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Expected Graduation *' }).fill('2026-09-02');
  await page.getByRole('button', { name: 'Resume Upload *' }).click();
  await page.getByRole('button', { name: 'Resume Upload *' }).setInputFiles('Rahul_S_RS_Design_Freelancer_Resume.pdf');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Data Structures');
  await page.getByRole('textbox', { name: 'Course Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Course Code' }).fill('CS 3001');
  await page.getByRole('textbox', { name: 'Course Code' }).press('Tab');
  await page.getByLabel('Grade Obtained *').selectOption('A');
  await page.getByLabel('Semester/Year').selectOption('Spring 2025');
  await page.getByRole('button', { name: 'Add Course' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Machine Learning');
  await page.getByRole('textbox', { name: 'Course Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Course Code' }).fill('CS 5001');
  await page.getByRole('textbox', { name: 'Course Code' }).press('Tab');
  await page.getByLabel('Grade Obtained *').press('ArrowDown');
  await page.getByLabel('Grade Obtained *').selectOption('A');
  await page.getByLabel('Grade Obtained *').press('Tab');
  await page.getByLabel('Semester/Year').selectOption('Spring 2025');
  await page.getByRole('button', { name: 'Add Course' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Job Title' }).click();
  await page.getByRole('textbox', { name: 'Job Title' }).fill('Data Intern');
  await page.getByRole('textbox', { name: 'Job Title' }).press('Tab');
  await page.getByRole('textbox', { name: 'Company Name' }).fill('Tech Company Inc.');
  await page.getByRole('textbox', { name: 'Company Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Date' }).fill('2024-01-01');
  await page.getByRole('textbox', { name: 'Start Date' }).press('Tab');
  await page.getByRole('textbox', { name: 'Start Date' }).press('Tab');
  await page.getByRole('checkbox', { name: 'Currently Working Here' }).check();
  await page.getByRole('textbox', { name: 'Description/Responsibilities' }).click();
  await page.getByRole('textbox', { name: 'Description/Responsibilities' }).fill('Data Scientist');
  await page.getByRole('button', { name: 'Add Experience' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('checkbox', { name: 'Python' }).check();
  await page.getByRole('checkbox', { name: 'SQL' }).check();
  await page.getByRole('checkbox', { name: 'Machine Learning' }).check();
  await page.getByRole('checkbox', { name: 'AWS' }).check();
  await page.getByRole('checkbox', { name: 'HTML/CSS' }).check();
  await page.getByRole('checkbox', { name: 'Git' }).check();
  await page.getByRole('checkbox', { name: 'JavaScript' }).check();
  await page.getByRole('checkbox', { name: 'Java', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Communication' }).check();
  await page.getByRole('checkbox', { name: 'Problem Solving' }).check();
  await page.getByRole('checkbox', { name: 'Teamwork' }).check();
  await page.getByRole('checkbox', { name: 'Adaptability' }).check();
  await page.getByRole('checkbox', { name: 'Time Management' }).check();
  await page.getByRole('radio', { name: 'Data Science' }).check();
  await page.getByText('Flexible (any semester)').click();
  await page.getByRole('textbox', { name: 'Any additional information' }).click();
  await page.getByRole('textbox', { name: 'Any additional information' }).fill('Interested in Data Science domain.');
  await page.getByRole('button', { name: 'Submit' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Save Draft' }).click();
});